### ISSUE TITLE
Vamos a pasarlo a Tailwindcss

### ISSUE THREAD

**Issue by marcoah** [marcoah/refer#2]
Vamos a pasar la interfaz basica de la consulta a Tailwindcss para empezar a practicar

**Comment by iamgdevvv** [comment]
Awesome project. i am sorry i cant understand what your issue is, but i think you want to use tailwindcss for your project? can i help you to do that and Would you mind if I pull this up for Hacktoberfest?

**Comment by marcoah** [comment]
Hi, i am testing how make a issue. But tomorrow i update readme.md with instructions. But the general idea is create a query in the BD using php for query and frontend with tailwind
